language: java
jdk:
 - oraclejdk7
 - openjdk7
before_install:
 - chmod +x gradlew
notifications:
  slack: openbaton:0mU0eqEY8Dcm0sWeFiGrKvFe
  email:
    - notifications@openbaton.org
cache:
  directories:
  - $HOME/.m2
script: 
 - ./gradlew build
after_success:
 - curl http://localhost:8080/ 
