#!/usr/bin/env bash
set -e
#
# This script allows you to install selfnet-vnfm. 
#
# 


export DEBIAN_FRONTEND=noninteractive
_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

_openbaton_log="/var/log/openbaton"

_user="$(id -un 2>/dev/null || true)"

function checkBinary {
  echo -n " * Checking for '$1'..."
  if command -v $1 >/dev/null 2>&1; then
     echo "OK"
     return 0
   else
     echo >&2 "FAILED."
     return 1
   fi
}

_ex='sh -c'
if [ "$_user" != 'root' ]; then
    if checkBinary sudo; then
        _ex='sudo -E sh -c'
    elif checkBinary su; then
        _ex='su -c'
    fi
fi

function prereq(){
    # TODO differentiate between fedora, OS X, ubuntu..
    $_ex 'apt-get update; apt-get -y install openjdk-7-jdk curl wget screen git'
}


function installMessageQueue() {
    echo "installing message queue.."
    $_ex 'apt-get install -y rabbitmq-server'
    ulimit -S -n 4096
    $_ex 'rabbitmqctl add_user admin openbaton'
    $_ex 'rabbitmqctl set_user_tags admin administrator'
    $_ex 'rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"'
    $_ex 'rabbitmq-plugins enable rabbitmq_management'
    $_ex 'service rabbitmq-server restart'
    if [ $? -ne 0 ]; then
      echo "ERROR: rabbitmq is not running properly (check the problem in /var/log/rabbitmq)"
      exit 1
    fi
}

function checkEnvironment {
  _error=0
  echo "Checking environment..."
  checkBinary java; _error=$(($_error + $?))
  checkBinary javac; _error=$(($_error + $?))
  checkBinary curl; _error=$(($_error + $?))
  checkBinary screen; _error=$(($_error + $?))
  checkBinary wget; _error=$(($_error + $?))
  if [ "0" != "$_error" ]; then
    echo >&2 "FAILED. Please install the above mentioned binaries."
    exit 1
  fi
}

function createOpenBatonLog {
    echo "Creating the OpenBaton Log folder"
    # removing it if exists
    $_ex 'rm -rf '$_openbaton_log
    $_ex 'mkdir -p '$_openbaton_log
    $_ex 'mkdir -p '$_openbaton_log/scriptsLog
    $_ex 'chown -R '"$_user $_openbaton_log"
}

function compileSelfnetVNFM {
    echo "compiling the Selfnet VNFM"
    ./selfnet-vnfm.sh compile
    if [ $? -ne 0 ]; then
        echo "ERROR: The compilation of the Selfnet VNFM failed"
        exit 1
    fi
    popd
}

function deploySelfnetVNFM {
    compileSelfnetVNFM
    #startSelfnetVNFM
}


function bootstrap {
    # install prerq
    prereq
    # message queue installation part
    #installMessageQueue
    # check if all the required libraries are available
    checkEnvironment
    # create log folder
    createOpenBatonLog
    # compile the Selfnet VNFM
    deploySelfnetVNFM
    echo "Selfnet-Vnfm installation completed."

}

bootstrap
